### ISSUE TITLE
Helper functions are no longer reserved words

### ISSUE THREAD

**Issue by lydell** [kchmck/vim-coffee-script#181]
Since jashkenas#3784 the helper functions, such as `__slice` and `__extends` are no longer reserved words, so there's no need highlighting them anymore.

**Comment by michaelficarra** [comment]
jashkenas/coffeescript#3784

**Comment by kchmck** [comment]
This should be fixed by b91dbe92ad794a85a03b089f384fa324ff4e0c3d
