### ISSUE TITLE
How to check for whitespace?

### ISSUE THREAD

**Issue by erichonkanen** [kchmck/vim-coffee-script#199]
Hello, does this "lint" coffeescript? with python I can press f7 to do flake8 but also it shows me whitespace that I should remove in realtime, does this also allow me to see whitespace in coffee files?

**Comment by sagax** [comment]
vim-coffee-script have the command CoffeeLint, but this command don't show error on code.

I just use ```coffeelint -f .setup_code_style.json path/to/file.coffee``` in terminal
