### ISSUE TITLE
import/export keywords support

### ISSUE THREAD

**Issue by sliceofcode** [kchmck/vim-coffee-script#207]
CoffeeScript just got import/export support. jashkenas/coffeescript#4300

[This may also be relevant.](https://github.com/jashkenas/coffeescript/commit/a8b77fb4e79e02cf5b39aa818df2166ca085875f#diff-45f508b714a4ac328c10a4c5a0e09dcaR59)

**Comment by kchmck** [comment]
This should be fixed in the syntax at least by fe0955a1a56d5d1a114604fb5cbb6f11b9677ca4
