### ISSUE TITLE
False-positive for comment character continuation

### ISSUE THREAD

**Issue by davidosomething** [kchmck/vim-coffee-script#208]
On lines where there is a continuation string and the second line begins with an interpolated variable:

``` coffee
      msg.send "`mine` to build your previous:
        #{userBuild.branch} on #{userBuild.target}"|
```

pressing 'o' (when `formatoptions+=o`)  to open a new line and continue comment characters results in a false-positive:

``` coffee
      msg.send "`mine` to build your previous:
        #{userBuild.branch} on #{userBuild.target}"
        #|
```

It thinks the interpolation symbol within the continued string is a comment character

**Comment by kchmck** [comment]
I guess the same thing happens with the python, es6, and lua plugins
```python
a = """
    # b"""
    #
```
```javascript
a = `
  // b`
//
```
```lua
a = [[
  -- b]]
  --
```
so I'm thinking it's just a vim annoyance due to the `'comments'` setting not taking syntax regions into account...

**Comment by davidosomething** [comment]
talking it over in #vim, remapping o/O to detect syntax group might be the way to go since there's no way to lookbehind (and definitely not performant way) to see if you're in a string
