### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by MnSx3** [kchmck/vim-coffee-script#221]
hey, 

I like the font you are using in the picture 

could you tell me the name of the font??

**Comment by kchmck** [comment]
Hey @MnSx3, that's good old [terminus](http://terminus-font.sourceforge.net/). On Arch I'm using it via the terminus-font-otb package. The OTB version seems important as I recently had to update to that due to [bitmap font issues with pango 1.44+](https://bbs.archlinux.org/viewtopic.php?id=248032).
